### ISSUE TITLE
Method expects 3 parameters, only 2 given

### ISSUE THREAD

**Issue by ametad** [cydrickn/geocoder-php-geocodexyz#1]
The next function that resides in the `GeocodeXyz` class expects 3 parameters:

```php
private function executeQuery(string $search, array $queryData, string $searchMode): AddressCollection
```

But in the same class where the `executeQuery` function is used, only 2 parameters are given:

```php
    public function geocodeQuery(GeocodeQuery $query): Collection
    {

        //

        return $this->executeQuery($address, $queryData);
    }
```

Sources:
https://github.com/cydrickn/geocoder-php-geocodexyz/blob/e90b75d426f8225fe5b5254622782b843f26274b/src/GeocodeXyz.php#L79
https://github.com/cydrickn/geocoder-php-geocodexyz/blob/e90b75d426f8225fe5b5254622782b843f26274b/src/GeocodeXyz.php#L88
https://github.com/cydrickn/geocoder-php-geocodexyz/blob/e90b75d426f8225fe5b5254622782b843f26274b/src/GeocodeXyz.php#L108

**Comment by cydrickn** [comment]
Hi,

Already removed the searchMode

The fix is included in https://github.com/cydrickn/geocoder-php-geocodexyz/releases/tag/v0.1.1
